apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
data:
  secretkey: eHFNczVoNmxkWFMwMXJSZ3IvZVVGRTVvbmsrVVR3UmRyckFWTVNmQ2dvOFB5Z0twR0JuUGFPa1hLQ0RMblJESQp1SUdjT3krUjJmM3Vsak01WlZwdjMxaFllYzlaMXBkaDY4ZWFUblFvNkhMOC8rWnVxNVRqcklZSU9XUGlxSnowCmRUL2I3VjlkZXFTQmlzMGRndmM4TkRHVnRiMnVkZlRoWDBkaGxSMFJlNzQ9
